name: Build Packages

on:
  push:
    tags:
      - 'v*'
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-deb:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up build environment
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential devscripts debhelper dh-python python3-all python3-setuptools libcairo2-dev pkg-config libgirepository1.0-dev gir1.2-gtk-3.0 gobject-introspection libgtk-3-dev libnotify-bin dbus-x11 python3-dev libglib2.0-dev
    
    - name: Set up Python for testing
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install Python dependencies for testing
      run: |
        python -m pip install --upgrade pip
        sudo apt-get install -y python3-psutil python3-xlib python3-notify2 python3-gi
        pip install PyGObject
    
    - name: Run CI tests
      run: |
        python3 tests/test-ci.py
    
    - name: Build Debian package
      run: |
        dpkg-buildpackage -b -us -uc
    
    - name: Upload Debian package artifacts
      uses: actions/upload-artifact@v4
      with:
        name: deb-package
        path: ../pomodoro-lock_*.deb
        retention-days: 30

  release:
    needs: [build-deb]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Download all artifacts
      uses: actions/download-artifact@v4
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          **/*.deb
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 