name: Test Build

on:
  pull_request:
    branches: [ main, master ]

permissions:
  contents: read

jobs:
  test-build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build wheel setuptools psutil python-xlib notify2 PyGObject
    
    - name: Run CI tests
      run: |
        python3 tests/test-ci.py
    
    - name: Test Python package build
      run: |
        python -m build
    
    - name: Test Debian package build
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential devscripts debhelper dh-python python3-all python3-setuptools
        dpkg-buildpackage -b -us -uc 